### ISSUE TITLE
Baza danych niezgodna ze specyfikacją

### ISSUE THREAD

**Issue by michupl22** [SoftonicaDev/softonica-backend#19]
Struktura bazy danych nie jest zgodna z najnowszą specyfikacją. Brakuje tabel, a niektóre są nadmiarowe. Więcej informacji w repozytorium [Softonica Database](https://github.com/SoftonicaDev/softonica-database).

## Struktura bazy danych

- [x] accounts
- [x] achievements
- [x] assignedtags
- [x] badges
- [x] collaborations
- [x] comments
- [x] contributors
- [x] experiences
- [x] forums
- [x] marketplaces
- [x] members
- [x] notifications
- [x] posts
- [x] products
- [x] profiles
- [x] projectcategories
- [x] projects
- [x] projecttypes
- [x] pucharses
- [x] ratings
- [x] releases
- [x] repositories
- [x] resetpasswords
- [x] services
- [x] skills
- [x] skilltypes
- [x] subscriptions
- [x] tags
- [x] teams
- [x] transactioncategories
- [x] transactions
- [x] users
- [x] verifications

**Comment by domKul** [comment]
zmienilem ```    `content`   TEXT(1024) NOT NULL ``` na TEXT i  w ```    `token`    VARCHAR(800) NOT NULL``` na 255

**Comment by michupl22** [comment]
Trzeba wszędzie zmienić na VARCHAR(512), ponieważ długość tokenu przeważnie nie przekracza 500 znaków, a w zapasie coś powinno być. Z kolei pole o tej długości nie przekracza limitu rozmiaru 3072 bajtów.
