### ISSUE TITLE
Zażądanie resetowania hasła

### ISSUE THREAD

**Issue by michupl22** [SoftonicaDev/softonica-backend#5]
Wysyła żądanie resetowania hasła.

- [x] Utworzyć Endpoint z danymi wejściowymi.
- [x] Zwracać odpowiedź w przypadku powodzenia operacji.
- [x] Zwracać odpowiedź w przypadku niepowodzenia operacji.

## Dane wejściowe
`POST` `/api/user/forgot-password`
```json
{
	"email" : "example@example.com"
}
```

## Odpowiedź
Powodzenie
```plain
200 OK
```
Niepowodzenie
```plan
500 Internal Server Error
```

**Comment by lukaszkosminski** [comment]
/api/user/request-change-password
